spring:
  application:
    name: support
  datasource:
    url: jdbc:postgresql://localhost:5858/dbsupport
    password: dbsupport
    username: dbsupport
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

